DROP DATABASE IF EXISTS blogr;
DROP DATABASE IF EXISTS blogr_test;
CREATE DATABASE blogr;
CREATE DATABASE blogr_test;
GRANT ALL PRIVILEGES ON DATABASE blogr TO ismail;
GRANT ALL PRIVILEGES ON DATABASE blogr_test TO ismail;
