"""empty message

Revision ID: 32c3d2d9891f
Revises: 58bfab0e4c09
Create Date: 2022-08-30 13:07:32.737283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c3d2d9891f'
down_revision = '58bfab0e4c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('users', sa.Column('signup_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'signup_date')
    op.drop_column('posts', 'is_published')
    # ### end Alembic commands ###
