"""add public id to Post and User

Revision ID: 69f856a929fa
Revises: cf5fc12804ce
Create Date: 2022-08-29 15:46:03.114565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f856a929fa'
down_revision = 'cf5fc12804ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('public_id', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('public_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_id')
    op.drop_column('posts', 'public_id')
    # ### end Alembic commands ###
